import { EnemyType, ArmorType } from './constants.js';

export const ENEMY_DATA = {
    [EnemyType.GRUNT]: {
        name: "Grunt",
        hp: 90,
        speed: 1.7,
        armor: ArmorType.UNARMORED,
        reward: 5,
        lives_cost: 1,
        is_flying: false,
        ability: null,
        size: 32,
        description: "Basic ground",
    },
    [EnemyType.RUNNER]: {
        name: "Runner",
        hp: 60,
        speed: 3.4,
        armor: ArmorType.UNARMORED,
        reward: 6,
        lives_cost: 1,
        is_flying: false,
        ability: null,
        size: 28,
        description: "Fast, fragile",
    },
    [EnemyType.TANK]: {
        name: "Tank",
        hp: 375,
        speed: 0.9,
        armor: ArmorType.PLATED,
        reward: 11,
        lives_cost: 1,
        is_flying: false,
        ability: null,
        size: 36,
        description: "Armored, slow",
    },
    [EnemyType.GHOST]: {
        name: "Ghost",
        hp: 150,
        speed: 1.4,
        armor: ArmorType.ETHEREAL,
        reward: 14,
        lives_cost: 1,
        is_flying: false,
        ability: "debuff_immune",
        size: 32,
        description: "Immune to slow",
    },
    [EnemyType.HEALER]: {
        name: "Healer",
        hp: 120,
        speed: 1.1,
        armor: ArmorType.UNARMORED,
        reward: 18,
        lives_cost: 1,
        is_flying: false,
        ability: "heal_aura",
        heal_amount: 15,
        heal_radius: 2.0,
        heal_cooldown: 3,
        size: 32,
        description: "Heals allies",
    },
    [EnemyType.WASP]: {
        name: "Wasp",
        hp: 45,
        speed: 2.8,
        armor: ArmorType.UNARMORED,
        reward: 8,
        lives_cost: 1,
        is_flying: true,
        ability: null,
        size: 24,
        description: "Flying enemy",
    },
    [EnemyType.DISRUPTOR]: {
        name: "Disruptor",
        hp: 180,
        speed: 1.1,
        armor: ArmorType.PLATED,
        reward: 20,
        lives_cost: 1,
        is_flying: false,
        ability: "disable_tower",
        disable_radius: 3.0,
        disable_duration: 3.0,
        disable_cooldown: 5.0,
        size: 32,
        description: "Disables towers",
    },
    [EnemyType.SUMMONER]: {
        name: "Summoner",
        hp: 225,
        speed: 1.0,
        armor: ArmorType.ETHEREAL,
        reward: 28,
        lives_cost: 2,
        is_flying: false,
        ability: "summon_on_death",
        summon_type: "imp",
        summon_count: 3,
        size: 36,
        description: "Spawns imps on death",
    },
    [EnemyType.IMP]: {
        name: "Imp",
        hp: 30,
        speed: 2.3,
        armor: ArmorType.UNARMORED,
        reward: 1,
        lives_cost: 0,
        is_flying: false,
        ability: null,
        size: 16,
        description: "Tiny, from summoner",
    },
    [EnemyType.BOSS]: {
        name: "Boss",
        hp: 1500,
        speed: 0.7,
        armor: ArmorType.ETHEREAL,
        reward: 100,
        lives_cost: 5,
        is_flying: false,
        ability: "tower_stun",
        stun_radius: 4.0,
        stun_duration: 2.0,
        stun_cooldown: 8.0,
        size: 64,
        description: "Powerful boss",
    },
};

export function scaleEnemyHP(baseHP, wave) {
    return baseHP * (1.0 + (wave - 1) * 0.18);
}

export function scaleEnemySpeed(baseSpeed, wave) {
    return baseSpeed * Math.min(1.0 + (wave - 1) * 0.025, 1.5);
}

export function scaleEnemyReward(baseReward, wave) {
    return Math.floor(baseReward * (1.0 + (wave - 1) * 0.06));
}
