import { TowerType, DamageType, TargetMode } from './constants.js';

export const TOWER_DATA = {
    [TowerType.ARROW]: {
        name: "Arrow",
        cost: 25,
        damage: 12,
        damage_type: DamageType.KINETIC,
        range: 4.0,
        fire_rate: 0.5,
        splash_radius: 0,
        target_mode: TargetMode.FIRST,
        can_hit_air: true,
        can_hit_ground: true,
        description: "Basic single-target",
        upgrade_costs: [15, 25, 40, 55, 75, 100, 130],
        projectile_speed: 12,
        specializations: {
            A: {
                name: "Sharpshooter",
                desc: "+50% dmg, +1 range",
                damage_mult: 1.5,
                range_bonus: 1,
            },
            B: {
                name: "Rapid Fire",
                desc: "0.2s fire rate",
                fire_rate: 0.2,
            },
        },
    },

    [TowerType.CANNON]: {
        name: "Cannon",
        cost: 50,
        damage: 45,
        damage_type: DamageType.EXPLOSIVE,
        range: 3.0,
        fire_rate: 1.5,
        splash_radius: 1.5,
        target_mode: TargetMode.FIRST,
        can_hit_air: false,
        can_hit_ground: true,
        description: "AoE cluster damage",
        upgrade_costs: [30, 45, 65, 85, 110, 140, 180],
        projectile_speed: 8,
        specializations: {
            A: {
                name: "Heavy Ordnance",
                desc: "+50% dmg, +1 AoE",
                damage_mult: 1.5,
                splash_bonus: 1.0,
            },
            B: {
                name: "Armor Piercer",
                desc: "3s armor break",
                armor_break: 3.0,
            },
        },
    },

    [TowerType.MAGE]: {
        name: "Mage",
        cost: 60,
        damage: 25,
        damage_type: DamageType.ENERGY,
        range: 3.5,
        requires_unlock: 'mage_tower',
        fire_rate: 1.0,
        splash_radius: 0,
        target_mode: TargetMode.FIRST,
        can_hit_air: true,
        can_hit_ground: true,
        description: "Strong vs Plated",
        upgrade_costs: [35, 50, 70, 95, 120, 155, 200],
        projectile_speed: 10,
        specializations: {
            A: {
                name: "Archmage",
                desc: "+50% dmg, chain 2",
                damage_mult: 1.5,
                chain_count: 2,
            },
            B: {
                name: "Pyromancer",
                desc: "10dps burn, 3s",
                burn_dps: 10,
                burn_duration: 3,
            },
        },
    },

    [TowerType.ICE]: {
        name: "Ice",
        cost: 40,
        damage: 5,
        damage_type: DamageType.FROST,
        range: 3.5,
        fire_rate: 1.2,
        splash_radius: 0,
        target_mode: TargetMode.FIRST,
        can_hit_air: true,
        can_hit_ground: true,
        description: "50% slow",
        slow_strength: 0.5,
        slow_duration: 2,
        upgrade_costs: [25, 40, 55, 75, 100, 130, 170],
        projectile_speed: 10,
        specializations: {
            A: {
                name: "Blizzard",
                desc: "AoE 2.0 slow",
                splash_radius: 2.0,
            },
            B: {
                name: "Permafrost",
                desc: "75% slow, 3s",
                slow_strength: 0.75,
                slow_duration: 3,
            },
        },
    },

    [TowerType.SKY_HUNTER]: {
        name: "Sky-Hunter",
        cost: 45,
        damage: 30,
        damage_type: DamageType.KINETIC,
        range: 5.0,
        fire_rate: 0.8,
        splash_radius: 0,
        target_mode: TargetMode.AIR_ONLY,
        can_hit_air: true,
        can_hit_ground: false,
        description: "Anti-air",
        upgrade_costs: [28, 42, 60, 80, 105, 135, 175],
        projectile_speed: 14,
        specializations: {
            A: {
                name: "Falcon Eye",
                desc: "+3 range",
                range_bonus: 3,
            },
            B: {
                name: "Strafing Run",
                desc: "3-shot burst",
                burst_count: 3,
                burst_delay: 0.1,
            },
        },
    },

    [TowerType.FLAME]: {
        name: "Flame",
        cost: 55,
        damage: 8,
        damage_type: DamageType.FIRE,
        range: 3.0,
        fire_rate: 0.8,
        splash_radius: 0,
        target_mode: TargetMode.FIRST,
        can_hit_air: false,
        can_hit_ground: true,
        description: "Burn 8dps, 3s",
        burn_dps: 8,
        burn_duration: 3,
        upgrade_costs: [32, 48, 68, 90, 115, 148, 190],
        projectile_speed: 9,
        specializations: {
            A: {
                name: "Inferno",
                desc: "AoE 2.0 burn, 15dps, 4s",
                splash_radius: 2.0,
                burn_dps: 15,
                burn_duration: 4,
            },
            B: {
                name: "Hellfire",
                desc: "2x burn, +2s",
                burn_dps_mult: 2,
                burn_duration_bonus: 2,
            },
        },
    },

    [TowerType.TESLA]: {
        name: "Tesla",
        cost: 65,
        damage: 18,
        damage_type: DamageType.ENERGY,
        range: 3.5,
        fire_rate: 1.0,
        splash_radius: 0,
        target_mode: TargetMode.FIRST,
        can_hit_air: true,
        can_hit_ground: true,
        description: "Chain 3 enemies",
        chain_count: 3,
        upgrade_costs: [38, 55, 78, 100, 130, 168, 215],
        projectile_speed: 11,
        specializations: {
            A: {
                name: "Storm Spire",
                desc: "6 chains, +50% dmg",
                chain_count: 6,
                damage_mult: 1.5,
            },
            B: {
                name: "Overcharge",
                desc: "Stun 0.5s on chain",
                chain_stun: 0.5,
            },
        },
    },

    [TowerType.SNIPER]: {
        name: "Sniper",
        cost: 75,
        damage: 50,
        damage_type: DamageType.KINETIC,
        range: 6.0,
        fire_rate: 2.5,
        splash_radius: 0,
        target_mode: TargetMode.STRONGEST,
        can_hit_air: true,
        can_hit_ground: true,
        description: "Massive damage, slow",
        upgrade_costs: [45, 65, 90, 120, 155, 200, 250],
        projectile_speed: 18,
        specializations: {
            A: {
                name: "Assassin",
                desc: "3x dmg to <30% HP",
                execute_mult: 3,
                execute_threshold: 0.3,
            },
            B: {
                name: "Siege Breaker",
                desc: "Ignore armor",
                ignore_armor: true,
            },
        },
    },

    [TowerType.HARRY_DUCK]: {
        name: "Harry Duck",
        cost: 120,
        damage: 0,
        damage_type: null,
        range: 5.0,
        fire_rate: 0,
        splash_radius: 0,
        target_mode: TargetMode.FIRST,
        can_hit_air: false,
        can_hit_ground: false,
        description: "Spawns duck soldiers",
        is_spawner: true,
        spawn_interval: 6,
        duck_hp: 80,
        duck_damage: 15,
        duck_speed: 1.8,
        upgrade_costs: [70, 100, 140, 185, 240, 300, 380],
        specializations: {
            A: {
                name: "Duck Army",
                desc: "Spawn 3 ducks",
                spawn_count: 3,
            },
            B: {
                name: "Mega Duck",
                desc: "1 giant duck, 3x stats",
                mega_duck: true,
                duck_hp_mult: 3,
                duck_damage_mult: 3,
                duck_size: 48,
            },
        },
    },

    [TowerType.AURA]: {
        name: "Aura",
        cost: 80,
        damage: 0,
        damage_type: null,
        range: 3.0,
        requires_unlock: 'aura_tower',
        fire_rate: 0,
        splash_radius: 0,
        target_mode: TargetMode.FIRST,
        can_hit_air: false,
        can_hit_ground: false,
        description: "Buffs nearby towers",
        is_support: true,
        aura_buff_options: ["attack_speed", "damage"],
        aura_attack_speed: 0.8,
        aura_damage: 0.15,
        upgrade_costs: [50, 75, 105, 140, 180, 230, 290],
        specializations: {
            A: {
                name: "War Banner",
                desc: "+2 range, +10% crit",
                range_bonus: 2,
                crit_chance: 0.1,
            },
            B: {
                name: "Sanctuary",
                desc: "Immune to disable",
                immunity: true,
            },
        },
    },

    [TowerType.GOLD_MINE]: {
        name: "Gold Mine",
        cost: 70,
        damage: 0,
        damage_type: null,
        range: 0,
        fire_rate: 0,
        splash_radius: 0,
        target_mode: TargetMode.FIRST,
        can_hit_air: false,
        can_hit_ground: false,
        description: "3g/5s, max 10",
        is_economy: true,
        gold_per_tick: 3,
        tick_interval: 5,
        upgrade_costs: [30, 50, 70, 90, 120, 155, 200],
        specializations: {
            A: {
                name: "Treasury",
                desc: "8g/5s",
                gold_per_tick: 8,
            },
            B: {
                name: "Mint",
                desc: "+50% nearby kill gold",
                kill_gold_bonus: 0.5,
                kill_gold_radius: 3.0,
            },
        },
    },

    [TowerType.DOOM_SPIRE]: {
        name: "Doom Spire",
        cost: 500,
        damage: 150,
        damage_type: DamageType.ENERGY,
        range: 6.0,
        fire_rate: 2.5,
        splash_radius: 0,
        target_mode: TargetMode.FIRST,
        can_hit_air: true,
        can_hit_ground: true,
        description: "AoE pulse hits all in range",
        is_aoe_pulse: true,
        upgrade_costs: [200, 250, 250, 250, 250, 250, 250],
        projectile_speed: 0,
        specializations: {
            A: {
                name: "Annihilation",
                desc: "2x dmg, death explosion",
                damage_mult: 2,
                death_explosion: true,
                death_explosion_pct: 0.5,
            },
            B: {
                name: "Vortex",
                desc: "Pull 1.5 tile, 60% slow 3s",
                vortex_pull: 1.5,
                vortex_slow: 0.6,
                vortex_slow_duration: 3,
            },
        },
    },
};

export const TOWER_ORDER = [
    TowerType.ARROW,
    TowerType.CANNON,
    TowerType.MAGE,
    TowerType.ICE,
    TowerType.SKY_HUNTER,
    TowerType.FLAME,
    TowerType.TESLA,
    TowerType.SNIPER,
    TowerType.HARRY_DUCK,
    TowerType.AURA,
    TowerType.GOLD_MINE,
    TowerType.DOOM_SPIRE,
];
